# Generated by Django 5.1.5 on 2025-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('BAR', 'Bar'), ('RESTAURANT', 'Restaurante'), ('PARTY', 'Festa')], default='PARTY', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
