# Generated by Django 5.1.5 on 2025-02-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='main_image',
        ),
    ]
