# Generated by Django 5.1.5 on 2025-01-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/cover_images/'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(default='sem imagem', upload_to='events/'),
            preserve_default=False,
        ),
    ]
