# Generated by Django 5.1.5 on 2025-02-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_image_event_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='main_image',
            new_name='image',
        ),
    ]
