# Generated by Django 5.1.5 on 2025-02-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='url',
            field=models.URLField(default='sem'),
            preserve_default=False,
        ),
    ]
