# Generated by Django 5.1.5 on 2025-02-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_autorizado_eventos',
            field=models.BooleanField(default=False),
        ),
    ]
