# Generated by Django 5.1.5 on 2025-02-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_autorizado_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_autorizado_eventos',
            field=models.BooleanField(default=False, verbose_name='Autorizado para Eventos'),
        ),
    ]
